#Model Config
backbone: ResNet50
batch-size: 32
epoch: 20
learning-rate: 0.001
scale-l2-regularizer: 0.01
dropout-rate: 0.5
checkpoint_path: "checkpoints/ResNet50/1/weights_7.h5"

#Database Config
train-path: '/home/socialab/Desktop/Bruno/CASIA-WebFace_aligned_mtcnn_224_train_test/train'
validation-path: '/home/socialab/Desktop/Bruno/CASIA-WebFace_aligned_mtcnn_224_train_test/test'
inputSize: 112

#Test Config
test-path: '/home/socialab/Desktop/Bruno/FaceRecognition/face_recognition_softmax/lfw_aligned_mtcnn_224/'
pairs-path: '/home/socialab/Desktop/Bruno/FaceRecognition/face_recognition_softmax/lfw_aligned_mtcnn_224/pairs_forTestInTrainning.txt'
test-type: 'Align-L2-CosineSim' #'Align'; 'Align-L2'; 'Align-L2-CosineSim'; 'Baseline'

